version: "3.8"
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map container's port 5000 to host's port 5000
    volumes:
      - .:/app       # Mount local project directory to container for live code updates
    environment:
      - FLASK_ENV=development